### ISSUE TITLE
Masking of credit card numbers in Purchase Theme API

### ISSUE THREAD

**Issue by dxdc** [ingenesis/shopp#3234] opened 2015-02-25 04:46 UTC
Minor issue: when masking credit card numbers that have last 4 digits starting with "0", e.g. "0668"... this reports correct in SQL database, but the first 0 is reported as "X" in the masked number.

E.g., "XXXXXXXXXXXXX668".

**Comment by jonathandavis** [comment] 2015-02-25 16:30
@dxdc are you using `1.3.x` branch or a released version of Shopp? I ask because a fix for PAN masking landed just recently: http://commit.shopp.net/aa7f041e

If you're not using the latest, we need to verify if this fix addresses this issue too (or not).

**Comment by jonathandavis** [comment] 2015-02-25 16:31
Anyone that can verify and report on this, your help is very much appreciated.

**Comment by dxdc** [comment] 2015-02-25 16:33
I'm using 1.3.8. I can try to implement this fix and test it, but an easier way would be to just change the SQL card entry to "0123" and send yourself an order receipt after doing that. I'll implement this fix too and hopefully that will help. thanks.

**Comment by jonathandavis** [comment] 2015-02-25 16:35
Oh ok, so this masking is taking place from the order viewing context, not during checkout?

**Comment by dxdc** [comment] 2015-02-25 16:39
Well, it's in the receipt (including the emailed one). Also, why is the length of $PAN checked to be >4 in this fix? This change might not store the card number for my Stripe JS implementation -- sent you an email about that.

**Comment by jonathandavis** [comment] 2015-02-25 16:44
The masking character can be changed using Theme API options, we can't rely on testing for mask characters, and we can't reliably differentiate between non-digit symbols (dashes for example) and mask characters. That leaves us to look at string length to determine if the submission was previously masked.

**Comment by dxdc** [comment] 2015-02-25 16:54
This makes sense, but shouldn't it be >= 4? I'm not seeing where the length of >4 is coming from and why that's relevant, although it seems like you're making the assumption that if only 4 digits are retained then the only reasonable explanation is PAN masking.

Isn't there a regex to search if the same character was repeated a certain number of times? This seems like a much better fix.

http://stackoverflow.com/questions/1660694/regular-expression-to-match-any-character-being-repeated-more-than-10-times

**Comment by jonathandavis** [comment] 2015-02-25 17:06
If you read the how the code is implemented, the evaluations there are testing to determine whether to update the session-stored PAN with what is coming from the form. In that case, anything `>= 4` would allow you to store the last 4 digits of the card. This is bad in every case except for Stripe (or other tokenized systems) because it would allow the 4-digit masked value of the PAN to become the actual value sent to other gateways as the card leading to lots of "invalid card number" errors for most other systems.

**Comment by dxdc** [comment] 2015-02-25 17:11
I understand. I think a better way to address it though is with this regex:

/(.)\1{12}/

This will catch if a PAN was used or not. The first order submit (Stripe or not) would be recorded into  $Billing->card. If there is a PAN, it can be assumed that the correct number was already stored into the db. This regex searches specifically for a PAN, and does not store it in the db if it finds one. The current implementation just removes the PAN along with any number of other non-numeric fields and will store any card number >4 digits. I think my solution is cleaner :)

**Comment by jonathandavis** [comment] 2015-02-25 17:11
I confirmed this is a separate issue.

**Comment by jonathandavis** [comment] 2015-02-25 17:16
@dxdc First, dealing with the issue first reported here, I've isolated it to only affecting the Purchase Theme API: `shopp('purchase.card')` (https://shopplugin.com/api/purchase-card/)

**Comment by jonathandavis** [comment] 2015-02-25 17:22
Regarding your comment on the approach for updating PANs, regex validation for PANs occurs ahead of this code (at the JS layer) and after this layer (during PHP validation). The code in question is about whether to keep/update the new input in the session. Validation is a separate concern.

The validation that is implemented uses card-type specific regex to ensure the value provided matches the card type.

**Closed** 2015-02-25 17:27 UTC
Labels: api, bug

**Comment by dxdc** [comment] 2015-02-25 17:38
@jonathandavis , awesome! thanks for the quick fix on this. And the other one too!

what I meant was that it sounds like you're only wanting to keep the new input in the session if it hasn't been masked out... right?

Right now, you're verifying masked input based on total num of digits. I'm proposed verifying if the input is masked with a different regex which looks specifically for the 12-character masking.

**Comment by jonathandavis** [comment] 2015-03-07 19:14
@dxdc Yes I understand your solution. Your regex checks for a repeating set of 12 characters. But regex is slow and CPU hungry. We avoid it when possible (at least we avoid it nowadays – there is old code that (ab)uses it). This would be a relatively low-impact situation. Still, l we save where we can.

Is there any case you can think of where checking for 4-digits is not going to work that the regex solution will? Make the case and we'll go for your solution and you can submit a PR (for the props) :)

**Comment by dxdc** [comment] 2015-03-09 05:03
Hi @jonathandavis -- sure, few cases I can think of.

The main one is submitting just a 4-digit CC number due to PCI-compliant gateways, like the Stripe token response, which is sure to be the preferred method as the industry moves forward. It allows for more flexibility of submitting a number of any length, and allows for different masking protocols should one be implemented at a later point.

Here's my fix:

```
+ if (!(preg_match('/(.)\1{11,}/', $form['card']))) $Billing->card = $PAN;
- if ( strlen($PAN) > 4 ) $Billing->card = $PAN;
```
