### ISSUE TITLE
1.3.x Discounts don't work without an end date

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3252] opened 2015-03-10 17:35 UTC
Vanilla Install, can't get any discount to work

I have tried several times....catalog, cart etc, all to no joy. This may be down to my set-up but I have gone through everything.

**Comment by sierrab123** [comment] 2015-03-11 22:25
Although the other 2 errors have gone on my new install, this one persists. Maybe my old xampp set up had had enough.

I still can't get Discounts to work in any way or for on wampserver

Vanilla everything

**Comment by sierrab123** [comment] 2015-03-12 17:14
Found the cause of the issue. I had only entered a start date. The default end date is 1970. So in this case the discount ended before it had started! Once I added an end date, all was rosy in the garden

I am not sure if this was an issue in previous versions as I can't recall having to enter end dates before

**Comment by sierrab123** [comment] 2015-03-12 17:18
Reopening as this may well be a bug for merchants with non ending discounts

**Comment by ben72** [comment] 2015-03-12 18:26
I don't see any issue with that if I just create a new discount like this:
https://www.dropbox.com/s/u52dj08a7mpxiqg/Selection_173.jpg?dl=0

My end date is not filled in, is yours?

**Comment by sierrab123** [comment] 2015-03-12 18:37
Without it filled in the discount would not function...I have not had this issue before as far as I can recall.

The logic in the discount leaves me confused...a default ending date that is 45 years ago (was that the day that DOS was invented?) and with a starting date of today should, to my mind be doomed from the moment you hit Save

**Comment by ben72** [comment] 2015-03-12 18:42
The discount does work for me when I don't enter any start or end date and just leave it blank.

Who cares about DOS? Unix time started 1 Jan 1970. :)

**Comment by crunnells** [comment] 2015-03-13 09:48
I have some unexplained issues with discounts also, but haven't figured out the problem yet. I'll post a follow up here when I do.

**Comment by jonathandavis** [comment] 2015-03-17 14:43
I could not reproduce this in 1.3.x. Without an end date provided (just a start date with the discount enabled), the discount worked right away.

The database does show the Epoch date + 1 second (1970-01-01 00:00:01) which is the correct value for no end date.

**Comment by jonathandavis** [comment] 2015-03-20 15:28
I can't reproduce this, so closing. Reopen if you have new information about the issue.

**Closed** 2015-03-20 15:28 UTC
Labels: bug, needs reporter
