### ISSUE TITLE
Selecting 'Cropped Images' in Image Details results in JS error

### ISSUE THREAD

**Issue by meredevelopment** [ingenesis/shopp#2412] opened 2013-09-09 17:17 UTC
If a 'cropped image' setting is selected on the Image Details colorbox within the Product Editor, the following js error is shown in Chrome Console: "Uncaught TypeError: Cannot read property 'element' of undefined" and refers to this code:
``` javascript
inst.element.css({left:d.left,top:d.top});
```
Firefox Console reports: "TypeError: C is undefined" and points to the jQuery.fn.scaleCrop function.
 
This has been reported by a customer (https://shopplugin.net/support/topic/javascript-error-typeerror-c-is-undefined) and replicated by me on a fresh 1.2.9 install, confirmed in IRC by Lorenzo. 

I've not found a solution yet.

**Comment by meredevelopment** [comment] 2015-12-16 09:20
I will confirm whether this is an issue or not still during my next 'Shopp' session.

**Comment by clifgriffin** [comment] 2016-02-20 22:58
This is a duplicate of #2679. Closing.

**Closed by clifgriffin** 2016-02-20 22:58 UTC
Labels: bug, duplicate
