### ISSUE TITLE
Last name not pulling over on checkout page

### ISSUE THREAD

**Issue by adamsewell** [ingenesis/shopp#3248] opened 2015-03-07 15:57 UTC
Shopp 1.3.8

When typing in the full name on the checkout page, it will only copy over the firstname. I believe it  has something to do with the way the selectors are being used in address.js. 

```javascript
$('#firstname,#lastname').change
```

A quick way to address this is to just remove #firstname as most people will have a last name.

**Comment by ben72** [comment] 2015-03-07 16:18
This looks like a duplicate of #3195

**Closed** 2015-03-09 02:08 UTC
Labels: duplicate
