### ISSUE TITLE
Dashboard reports showing 0.00 for 30 day view

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3565] opened 2016-07-17 22:43 UTC
There are a couple of views (30 days in particular) that show 0.00 on the dashboard reports for Shopp 1.3.11.

**Comment by Just-m** [comment] 2016-07-18 07:41
I can't replicate this. There is some delay in the updating of the dashboard stats due to a set transient, but other than that numbers seem to add up fine.

I might be using other settings though.

**Comment by sierrab123** [comment] 2016-07-18 09:07
I can confirm sales stats issue but the sales report is fine

**Comment by sierrab123** [comment] 2016-07-18 09:26
Checking them one at a time....

This Week works, whilst the other do not in that dropdown

Lifetime works consistently

However, I just checked on my 1310 install and that also has issues with the sales stats. In that install This week shows zero sales, whilst the rest of the dropdown is correct. The complete opposite!!

**Comment by Just-m** [comment] 2016-07-18 10:51
When you look at this file \core\flow\Dashboard.php: you will see there are different delays set for the different views. Are you sure it is not just delayed instead of not working?

**Comment by sierrab123** [comment] 2016-07-18 17:15
Fixed by https://github.com/ingenesis/shopp/pull/3566

**Closed by sierrab123** 2016-07-18 17:15 UTC
