### ISSUE TITLE
WP 4.4 upgrade causes Fatal Error on Shopp Orders page

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3410] opened 2015-12-09 07:12 UTC
Fatal error: Call to a member function render_screen_reader_content() on a non-object in C:\wamp\www\Shopp139\wp-admin\includes\class-wp-list-table.php on line 760

The update seems to effect one page of the Shopp plugin which returns the above error.

As far as I can see everything else is fine with the plugin and the rest of the site

The issue can be worked around by temporarily reverting to 4.3.1

**Comment by meredevelopment** [comment] 2015-12-09 11:30
I've just seen this problem on the Products page. In that case it was [this line](https://github.com/ingenesis/shopp/blob/master/core/ui/products/products.php#L42):
`<?php $ListTable->pagination('top'); ?>`

Changing that to:

`<?php $ListTable->pagination(); ?>` 

seems to 'fix' the problem. Using the value 'top' triggers this if statement in wp-admin\includes\class-wp-list-table.php, and [which is new to WP4.4](https://github.com/WordPress/WordPress/commit/0c2b2a0e3dd57ba9c02f5d9022a26481cb970587#diff-4f0987d253a0fd95c723c5ff5969f276):
``` php
if ( 'top' === $which && $total_pages > 1 ) {
	$this->screen->render_screen_reader_content( 'heading_pagination' );
}
```

That's as far as I've got. A hacky fix is removing the 'top' value, but that's not a real solution.

**Comment by WriteCraft** [comment] 2015-12-09 17:00
I also get a different fatal error on the Shopp > Catalog > Categories page, do you?

Error Message

Fatal Error: Call to undefined method ProductCategory::filter() in /xd1/homes/hash/86/09/a10986/05/20/u102005/sobaymaps.com/www/wp-includes/taxonomy.php on line 802
Description

The WordPress code created an error that caused PHP execution to fail. This typically happens when the WordPress code has been modified.

The code tried to run a function that doesn't exist (ProductCategory::filter()). This type of error is typically caused by a simple typo (is_hom() rather than is_home()), by calling a function provided by a plugin when that plugin is not activated, by calling a function before it is ready (such as calling a function before the code that creates it has run), or by using a function that no longer exists (the function may have been removed from WordPress core or the plugin/theme that previously supplied it).

**Comment by jonathandavis** [comment] 2015-12-10 03:05
Fixed with commit 10f0d11 on the 1.3.x branch.

This fix needs verified before we can do an emergency 1.3.10 release.

**Comment by sierrab123** [comment] 2015-12-10 06:43
Looking Good on testing

**Comment by meredevelopment** [comment] 2015-12-10 09:24
Yep yep yeppity yep @jonathandavis that looks good! All the areas that were broken previously are fixed as far as I can see, and I've run through a couple of test orders to check nothing else is broken. Not done exhaustive testing you understand, but I'll be happy to put this live on two sites when you release it.

Thanks!

:neckbeard: :thought_balloon: 
If someone else needs to test this and is unsure how, I think the easiest way (assuming Git is present on the server, and one has access to the command-line / CLI / Terminal) is to:
1) Deactivate Shopp in WordPress plugins.
2) Rename the 'shopp' directory in wp-content/plugins directory on the server to 'shopp-139'.
3) Clone just the 1.3.x branch into a new 'shopp' directory with this command on the command line:
`git clone -b 1.3.x --single-branch git@github.com:ingenesis/shopp.git shopp`.
4) Activate the new Shopp plugin (mouse-over the activate link to check it's the new one and not shopp-139.

**Comment by podoglyph** [comment] 2015-12-10 18:24
Hi, is there any update on the 1.3.10 release?

**Comment by sierrab123** [comment] 2015-12-10 19:44
Testing has been good so far and hopefully it will be pushed out overnight

**Comment by rickgregory** [comment] 2015-12-11 06:28
Hate to say this but I just added a product, assigned it to a category, saved. Added variations, Updated and the Products screen tells me there's a product there but is blank. No debug messages though. This is the 1.3.10 branch, WP 4.4

**Comment by sierrab123** [comment] 2015-12-11 08:07
I followed your steps and found that whilst the buttons do not show when you hover the items, you can click on the product and edit it. The product exists in the back end and front end.

**Comment by meredevelopment** [comment] 2015-12-11 09:45
@rickgregory Hi, sorry I can't replicate that. Please let us know about any other plugins and the theme as per my notes in the other issue. Thanks!

**Comment by meredevelopment** [comment] 2015-12-11 13:12
@jonathandavis this branch introduced a tiny CSS bug, fixed here: https://github.com/ingenesis/shopp/pull/3413 - If I've done that wrong, please let me know, or just fix it in your work before 1.3.10 is released.

**Comment by rickgregory** [comment] 2015-12-11 18:00
I love this. Downloaded the plugin off the commit link above and... all is well. Can't replicate even with t he plugins and themes so I have to assume something was messed up about the download I had last night. Sorry for the false alarm.

**Comment by sierrab123** [comment] 2015-12-12 19:41
All working fine with that css fix from @meredevelopment

**Comment by AnotherTurn** [comment] 2015-12-14 00:28
What I got:

Products admin page displays but no action buttons under the title

Categories admin page does not display

I've just done a recent update to Shopp 1.3.9 after upgrading from 1.2.9. I used the ZIP file downloaded from the website, not from WP plugins site. It says I'm running 1.3.9.

I made the 8-file edits, even copying over the entire contents of categories.php from the fix for commit https://github.com/ingenesis/shopp/commit/10f0d112aea5de7b308505d5ffd1c9472818c1ef but it doesn't work for me. I don't get a fatal error, the page is merely blank (no title or contents).

**Comment by rickgregory** [comment] 2015-12-14 01:02
I'd just grab the entire build from the 10f0d11
<https://github.com/ingenesis/shopp/commit/10f0d112aea5de7b308505d5ffd1c9472818c1ef>
link vs trying to do edits to your existing 1.3.9

**Comment by sierrab123** [comment] 2015-12-14 07:54
The zip download (for whatever reason) of the 1.3 branch does not guarantee a  current up to date version of 1.3 (1.3.10 pre-release). I cloned Shopp locally using Git Hub for Windows and then chose the 1.3 branch, opened in explorer and uploaded that.. This includes https://github.com/ingenesis/shopp/pull/3413 a fix for the missing edit buttons

**Comment by ben72** [comment] 2015-12-14 22:03
@jonathandavis Tested with WP4.4, saw the order issues then:
git clone --branch="1.3.x" https://github.com/ingenesis/shopp.git
and made a successful purchase using Stripe. So onsite gw tested OK!

**Comment by clifgriffin** [comment] 2015-12-15 14:43
@jonathandavis can you confirm that all WP 4.4 fixes are in master before we close this?

**Comment by jonathandavis** [comment] 2015-12-15 15:25
Confirmed. The new admin structure in master moved Shopp away from the private table helper class that was the source of issues in 1.3.

**Closed by jonathandavis** 2015-12-15 15:25 UTC
Labels: bug, critical
